variables:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: teasaita/nonotes_app
  TAG_LATEST: $IMAGE_REGISTRY/$IMAGE_NAME:latest
  TAG_COMMIT: $IMAGE_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:latest
  services:
    - docker:latest
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $IMAGE_REGISTRY

stages:
  - build
  - test
  - deploy

build:commit:
  stage: build
  script:
    - docker build --force-rm -t $TAG_COMMIT .
    - docker push $TAG_COMMIT
  after_script:
    # - docker images | grep nonotes
    # - docker rmi -f $(docker images -q --filter "reference='nonotes-app'")
    # - docker rmi -f $IMAGE_NAME:$CI_COMMIT_SHORT_SHA

build:latest:
  stage: build
  script:
    - docker build --force-rm -t $TAG_LATEST .
    - docker push $TAG_LATEST
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  after_script:
    - docker rmi $IMAGE_NAME:latest

tests:bundle-audit:
  stage: test
  variables:
    COMPOSE_FILE: envs/tests/docker-compose.yml
  before_script:
  - export IMAGE_NAME="$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  script:
    - docker pull $TAG_COMMIT
    - docker-compose up -d
    - docker-compose exec app bundle-audit check
  after_script:
    - docker-compose down -v --remove-orphans || true

tests:units:
  stage: test
  variables:
    COMPOSE_FILE: envs/tests/docker-compose.yml
  before_script:
  - export IMAGE_NAME="$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  script:
    - docker pull $TAG_COMMIT
    - docker-compose up -d
    - docker-compose exec app bundle exec rspec spec
  after_script:
    - docker-compose down -v --remove-orphans || true

deploy:prod:
  stage: deploy
  script:
    - echo "deploy"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'