# stages:
#   - build
#   - test

# build:
#   stage: build

#   before_script:
#     - docker login -u Deployer -p ${ACCESS_TOKEN} registry.gitlab.com

#   script:
#     - docker-compose build --pull --force-rm && docker-compose push

# test:
#   stage: test
# - docker login -u GitlabDeployToken -p ${REGISTRY_ACCESS_TOKEN} ${CI_REGISTRY}


variables:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: teasaita/nonotes_app
  TAG_LATEST: $IMAGE_REGISTRY/$IMAGE_NAME:latest
  TAG_COMMIT: $IMAGE_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $IMAGE_REGISTRY


stages:
  - build

build:
  stage: build
  script:
    - docker pull $TAG_LATEST || true
    - docker build --cache-from $TAG_LATEST -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT