# stages:
#   - build
#   - test

# build:
#   stage: build

#   before_script:
#     - docker login -u Deployer -p ${ACCESS_TOKEN} registry.gitlab.com

#   script:
#     - docker-compose build --pull --force-rm && docker-compose push

# test:
#   stage: test
# - docker login -u GitlabDeployToken -p ${REGISTRY_ACCESS_TOKEN} ${CI_REGISTRY}


default:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN


stages:
  - build

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/nonotes/nonotes_api_rails/nonotes_app:latest .
    - docker push $CI_REGISTRY/nonotes/nonotes_api_rails/nonotes_app:latest
    