variables:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: teasaita/nonotes_app
  TAG_LATEST: $IMAGE_REGISTRY/$IMAGE_NAME:latest
  TAG_COMMIT: $IMAGE_REGISTRY/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $IMAGE_REGISTRY

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker pull $TAG_LATEST || true
    - docker build --cache-from $TAG_LATEST -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT

# rubocop:bundle_audit:
#   stage: test
#   image: 
#   script: |
#     gem install bundler-audit
#     bundle-audit update
#     bundle-audit check

tests:units:
  stage: test
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker-compose up -d
    - sleep 3
    - docker-compose exec app rspec spec
  after_script:
    - docker-compose down -v --remove-orphans || true